export interface Oportunidad {
  id: string;
  slug: string;
  titulo: string;
  organizacion: string;
  organizacionId: string;
  logo: string;
  ubicacion: string;
  modalidad: string;
  tipo: string;
  categoria: string;
  fechaLimite: string;
  descripcion: string;
  fechaPublicacion: string;
  estado: string;
}

export const OPORTUNIDADES: Oportunidad[] = [
  {
    id: '1',
    slug: 'pasantia-frontend-angular',
    titulo: 'Pasantía Frontend Angular',
    organizacion: 'Empresa XYZ',
    organizacionId: 'org-xyz',
    logo: 'https://placehold.co/100x100/4f46e5/white?text=XYZ',
    ubicacion: 'Oruro',
    modalidad: 'Remoto',
    tipo: 'Pasantía',
    categoria: 'Desarrollo Web',
    fechaLimite: '2026-09-30',
    descripcion:
      'Buscamos un estudiante o recién egresado apasionado por el desarrollo web frontend para unirse a nuestro equipo de software.',
    fechaPublicacion: 'Hace 2 días',
    estado: 'Aprobada',
  },
  {
    id: '2',
    slug: 'desarrollador-web-junior',
    titulo: 'Desarrollador Web Junior',
    organizacion: 'Empresa ABC',
    organizacionId: 'org-abc',
    logo: 'https://placehold.co/100x100/10b981/white?text=ABC',
    ubicacion: 'Oruro',
    modalidad: 'Presencial',
    tipo: 'Empleo Junior',
    categoria: 'Desarrollo Web',
    fechaLimite: '2026-09-25',
    descripcion:
      'Excelente oportunidad para egresados interesados en consolidar su carrera en desarrollo de software fullstack.',
    fechaPublicacion: 'Hace 3 días',
    estado: 'Aprobada',
  },
  {
    id: '3',
    slug: 'beca-formacion-fullstack-cloud',
    titulo: 'Beca Formación Fullstack Cloud',
    organizacion: 'Fundación Estrella del Sur',
    organizacionId: 'org-estrella',
    logo: 'https://placehold.co/100x100/f59e0b/white?text=FES',
    ubicacion: 'La Paz',
    modalidad: 'Remoto',
    tipo: 'Beca',
    categoria: 'Capacitación',
    fechaLimite: '2026-10-15',
    descripcion:
      'Beca integral para jóvenes talentos interesados en especializarse en desarrollo cloud.',
    fechaPublicacion: 'Hace 1 día',
    estado: 'Aprobada',
  },
  {
    id: '4',
    slug: 'voluntariado-educativo-stem',
    titulo: 'Voluntariado Educativo STEM',
    organizacion: 'TechBolivia Community',
    organizacionId: 'org-techbolivia',
    logo: 'https://placehold.co/100x100/ec4899/white?text=TB',
    ubicacion: 'Cochabamba',
    modalidad: 'Híbrido',
    tipo: 'Voluntariado',
    categoria: 'Educación',
    fechaLimite: '2026-09-20',
    descripcion: 'Mentoría para enseñar programación básica a estudiantes de colegio.',
    fechaPublicacion: 'Hace 5 días',
    estado: 'Aprobada',
  },
  {
    id: '5',
    slug: 'pasantia-diseno-ui-ux',
    titulo: 'Pasantía Diseño UI/UX',
    organizacion: 'SoftStudio Bolivia',
    organizacionId: 'org-softstudio',
    logo: 'https://placehold.co/100x100/8b5cf6/white?text=SS',
    ubicacion: 'Santa Cruz',
    modalidad: 'Remoto',
    tipo: 'Pasantía',
    categoria: 'Diseño',
    fechaLimite: '2026-10-01',
    descripcion: 'Prototipado de aplicaciones web y móviles atractivas en Figma.',
    fechaPublicacion: 'Hace 4 días',
    estado: 'Aprobada',
  },
  {
    id: '6',
    slug: 'asistente-marketing-digital',
    titulo: 'Asistente de Marketing Digital',
    organizacion: 'Fundación Estrella del Sur',
    organizacionId: 'org-estrella',
    logo: 'https://placehold.co/100x100/f59e0b/white?text=FES',
    ubicacion: 'Oruro',
    modalidad: 'Presencial',
    tipo: 'Empleo Junior',
    categoria: 'Marketing',
    fechaLimite: '2026-09-18',
    descripcion: 'Apoyo en redes sociales y creación de contenido institucional.',
    fechaPublicacion: 'Hace 1 semana',
    estado: 'Aprobada',
  },
  {
    id: '7',
    slug: 'pasantia-soporte-ti',
    titulo: 'Pasantía en Soporte TI',
    organizacion: 'Andes Tecnología',
    organizacionId: 'org-andes',
    logo: 'https://placehold.co/100x100/0f766e/white?text=AT',
    ubicacion: 'Oruro',
    modalidad: 'Presencial',
    tipo: 'Pasantía',
    categoria: 'Tecnología',
    fechaLimite: '2026-10-05',
    descripcion:
      'Apoyo en mantenimiento de equipos, instalación de software y atención de incidencias técnicas.',
    fechaPublicacion: 'Hace 2 días',
    estado: 'Aprobada',
  },
  {
    id: '8',
    slug: 'desarrollador-frontend-junior',
    titulo: 'Desarrollador Frontend Junior',
    organizacion: 'NovaSoft',
    organizacionId: 'org-novasoft',
    logo: 'https://placehold.co/100x100/2563eb/white?text=NS',
    ubicacion: 'La Paz',
    modalidad: 'Híbrido',
    tipo: 'Empleo Junior',
    categoria: 'Desarrollo Web',
    fechaLimite: '2026-10-10',
    descripcion:
      'Buscamos desarrollador junior con conocimientos de HTML, CSS, TypeScript y frameworks frontend.',
    fechaPublicacion: 'Hace 3 días',
    estado: 'Aprobada',
  },
  {
    id: '9',
    slug: 'beca-desarrollo-aplicaciones-web',
    titulo: 'Beca en Desarrollo de Aplicaciones Web',
    organizacion: 'Fundación Futuro Digital',
    organizacionId: 'org-futuro-digital',
    logo: 'https://placehold.co/100x100/9333ea/white?text=FD',
    ubicacion: 'Cochabamba',
    modalidad: 'Remoto',
    tipo: 'Beca',
    categoria: 'Capacitación',
    fechaLimite: '2026-10-20',
    descripcion:
      'Programa de formación dirigido a estudiantes interesados en desarrollo frontend y backend.',
    fechaPublicacion: 'Hace 4 días',
    estado: 'Aprobada',
  },
  {
    id: '10',
    slug: 'voluntariado-alfabetizacion-digital',
    titulo: 'Voluntariado en Alfabetización Digital',
    organizacion: 'Jóvenes por Bolivia',
    organizacionId: 'org-jovenes-bolivia',
    logo: 'https://placehold.co/100x100/e11d48/white?text=JB',
    ubicacion: 'Oruro',
    modalidad: 'Presencial',
    tipo: 'Voluntariado',
    categoria: 'Educación',
    fechaLimite: '2026-09-28',
    descripcion:
      'Apoya en talleres de informática básica dirigidos a jóvenes y adultos de diferentes comunidades.',
    fechaPublicacion: 'Hace 6 días',
    estado: 'Aprobada',
  },
  {
    id: '11',
    slug: 'disenador-ui-ux-junior',
    titulo: 'Diseñador UI/UX Junior',
    organizacion: 'PixelLab Bolivia',
    organizacionId: 'org-pixellab',
    logo: 'https://placehold.co/100x100/db2777/white?text=PL',
    ubicacion: 'Santa Cruz',
    modalidad: 'Híbrido',
    tipo: 'Empleo Junior',
    categoria: 'Diseño',
    fechaLimite: '2026-10-08',
    descripcion:
      'Participa en el diseño de interfaces y prototipos para aplicaciones web utilizando Figma.',
    fechaPublicacion: 'Hace 1 semana',
    estado: 'Aprobada',
  },
  {
    id: '12',
    slug: 'pasantia-marketing-redes-sociales',
    titulo: 'Pasantía en Marketing y Redes Sociales',
    organizacion: 'Impulso Creativo',
    organizacionId: 'org-impulso',
    logo: 'https://placehold.co/100x100/ea580c/white?text=IC',
    ubicacion: 'La Paz',
    modalidad: 'Remoto',
    tipo: 'Pasantía',
    categoria: 'Marketing',
    fechaLimite: '2026-09-29',
    descripcion:
      'Apoyo en planificación de contenido, gestión de redes sociales y campañas digitales.',
    fechaPublicacion: 'Hace 3 días',
    estado: 'Aprobada',
  },
  {
    id: '13',
    slug: 'pasantia-desarrollo-backend',
    titulo: 'Pasantía Desarrollo Backend',
    organizacion: 'CodeLabs Bolivia',
    organizacionId: 'org-codelabs',
    logo: 'https://placehold.co/100x100/1d4ed8/white?text=CL',
    ubicacion: 'Cochabamba',
    modalidad: 'Remoto',
    tipo: 'Pasantía',
    categoria: 'Desarrollo Web',
    fechaLimite: '2026-10-12',
    descripcion:
      'Participa en el desarrollo de APIs y servicios para aplicaciones web junto a nuestro equipo técnico.',
    fechaPublicacion: 'Hace 1 día',
    estado: 'Aprobada',
  },
  {
    id: '14',
    slug: 'programa-formacion-ciberseguridad',
    titulo: 'Programa de Formación en Ciberseguridad',
    organizacion: 'Bolivia Secure',
    organizacionId: 'org-bolivia-secure',
    logo: 'https://placehold.co/100x100/334155/white?text=BS',
    ubicacion: 'Oruro',
    modalidad: 'Híbrido',
    tipo: 'Beca',
    categoria: 'Capacitación',
    fechaLimite: '2026-10-25',
    descripcion:
      'Programa introductorio sobre seguridad informática, protección de datos y buenas prácticas digitales.',
    fechaPublicacion: 'Hoy',
    estado: 'Aprobada',
  },
  {
    id: '15',
    slug: 'asistente-diseno-grafico',
    titulo: 'Asistente de Diseño Gráfico',
    organizacion: 'Creativa Studio',
    organizacionId: 'org-creativa',
    logo: 'https://placehold.co/100x100/7c3aed/white?text=CS',
    ubicacion: 'Santa Cruz',
    modalidad: 'Presencial',
    tipo: 'Empleo Junior',
    categoria: 'Diseño',
    fechaLimite: '2026-10-03',
    descripcion:
      'Apoyo en elaboración de material gráfico, contenido digital y piezas para redes sociales.',
    fechaPublicacion: 'Hace 5 días',
    estado: 'Aprobada',
  },
  {
    id: '16',
    slug: 'voluntariado-mentor-programacion',
    titulo: 'Voluntariado como Mentor de Programación',
    organizacion: 'Código para Todos',
    organizacionId: 'org-codigo-todos',
    logo: 'https://placehold.co/100x100/059669/white?text=CT',
    ubicacion: 'La Paz',
    modalidad: 'Remoto',
    tipo: 'Voluntariado',
    categoria: 'Educación',
    fechaLimite: '2026-10-18',
    descripcion:
      'Comparte tus conocimientos de programación básica acompañando a estudiantes que están comenzando en tecnología.',
    fechaPublicacion: 'Hace 2 días',
    estado: 'Aprobada',
  },
  {
    id: '17',
    slug: 'analista-datos-junior',
    titulo: 'Analista de Datos Junior',
    organizacion: 'DataBol',
    organizacionId: 'org-databol',
    logo: 'https://placehold.co/100x100/0284c7/white?text=DB',
    ubicacion: 'Oruro',
    modalidad: 'Híbrido',
    tipo: 'Empleo Junior',
    categoria: 'Tecnología',
    fechaLimite: '2026-10-14',
    descripcion:
      'Apoyo en análisis de información, elaboración de reportes y visualización de datos para proyectos empresariales.',
    fechaPublicacion: 'Hace 4 días',
    estado: 'Aprobada',
  },
  {
    id: '18',
    slug: 'pasantia-community-manager',
    titulo: 'Pasantía Community Manager',
    organizacion: 'MediaLab',
    organizacionId: 'org-medialab',
    logo: 'https://placehold.co/100x100/c026d3/white?text=ML',
    ubicacion: 'Cochabamba',
    modalidad: 'Remoto',
    tipo: 'Pasantía',
    categoria: 'Marketing',
    fechaLimite: '2026-10-06',
    descripcion:
      'Apoyo en gestión de comunidades digitales, creación de publicaciones y seguimiento de métricas.',
    fechaPublicacion: 'Hace 1 semana',
    estado: 'Aprobada',
  },
];
